// <auto-generated />
using System;
using EReceteAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EReceteAPI.Migrations
{
    [DbContext(typeof(EReceteDBContext))]
    partial class EReceteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EReceteAPI.Database.Entities.Ilac", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("AdArama");

                    b.Property<string>("AtcAd");

                    b.Property<string>("AtcKod");

                    b.Property<long>("Barkod");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CreatedKurumKodu");

                    b.Property<long?>("CreatedRoleId");

                    b.Property<string>("FirmaAd");

                    b.Property<decimal?>("Fiyat");

                    b.Property<int?>("GeriOdeme");

                    b.Property<int?>("IlacReceteRengi");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<long?>("ReceteID");

                    b.Property<int?>("ReceteTuru");

                    b.Property<string>("RowGuid");

                    b.Property<string>("SessionId");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<int?>("UpdatedKurumKodu");

                    b.Property<long?>("UpdatedRoleId");

                    b.Property<string>("UpdatedSessionId");

                    b.HasKey("Id");

                    b.HasIndex("ReceteID");

                    b.ToTable("Ilac");
                });

            modelBuilder.Entity("EReceteAPI.Database.Entities.Recete", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CreatedKurumKodu");

                    b.Property<long?>("CreatedRoleId");

                    b.Property<string>("ReceteNo");

                    b.Property<DateTime?>("ReceteTarih");

                    b.Property<int?>("ReceteTuru");

                    b.Property<string>("RowGuid")
                        .HasMaxLength(36);

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedDate");

                    b.Property<int?>("UpdatedKurumKodu");

                    b.Property<long?>("UpdatedRoleId");

                    b.HasKey("ID");

                    b.ToTable("Recete","Muayene");
                });

            modelBuilder.Entity("EReceteAPI.Database.Entities.Users", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad");

                    b.Property<string>("CepTelefonu");

                    b.Property<string>("DiplomaNo");

                    b.Property<string>("Email");

                    b.Property<string>("EsaglikPassword");

                    b.Property<string>("MernisSifresi");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Sgksifresi");

                    b.Property<string>("Soyad");

                    b.Property<long>("TckimlikNo");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EReceteAPI.Database.Entities.Ilac", b =>
                {
                    b.HasOne("EReceteAPI.Database.Entities.Recete")
                        .WithMany("Ilaclar")
                        .HasForeignKey("ReceteID");
                });
#pragma warning restore 612, 618
        }
    }
}
